
const USER = "USER";

export const TOGGLE_HEADER = "TOGGLE_HEADER";

export const LOGOUT = "LOGOUT";

export const LOGIN_MODAL_OPEN = "LOGIN_MODAL_OPEN";
export const LOGIN_MODAL_CLOSE = "LOGIN_MODAL_CLOSE";

export const REGISTER_MODAL_OPEN = "REGISTER_MODAL_OPEN";
export const REGISTER_MODAL_CLOSE = "REGISTER_MODAL_CLOSE";

export const FORGET_PASSWORD_MODAL_OPEN = "FORGET_PASSWORD_MODAL_OPEN";
export const FORGET_PASSWORD_MODAL_CLOSE = "FORGET_PASSWORD_MODAL_CLOSE";

export const PROFILE_MODAL_OPEN = "PROFILE_MODAL_OPEN";
export const PROFILE_MODAL_CLOSE = "PROFILE_MODAL_CLOSE";


export default USER;    